/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\theme\matchaTheme.ts
 * Command: astryx theme build src\theme\matchaTheme.ts --out src\theme\perfect-six.css
 * Generated: 2026-07-20T15:43:11.678Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const matchaIconRegistry: IconRegistry;
export declare const perfectSixTheme: DefinedTheme;
